version: '3'
services:
  #dev-bleisure:
    #image: mysql:8.0
    ports:
        #- 3305:3306
    environment:
        #MYSQL_ROOT_PASSWORD: root
        #MYSQL_DATABASE: bleisure
  nest:
    build:
      context: .  # La ruta al directorio donde se encuentra tu Dockerfile
      dockerfile: Dockerfile  # El nombre de tu Dockerfile
    ports:
      - '8080:8080' # Mapeo del puerto del contenedor NestJS al puerto del host
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      AGENT_SINE: ${AGENT_SINE}
      TERMINAL_ID: ${TERMINAL_ID}
      TARGET: ${TARGET}
      ISOCOUNTRY: ${ISOCOUNTRY}
      PROD: ${PROD}
      REDISS_STRING: ${REDISS_STRING}

