version: '3'
services:
  redis:
    image: redis:latest
    container_name: mi-redis-container
    ports:
      - '6379:6379' # Mapeo del puerto del contenedor Redis al puerto del host

  nestjs-app:
    build: . # Ruta al Dockerfile
    ports:
      - '3030:3030' # Mapeo del puerto del contenedor NestJS al puerto del host
    environment:
      REDIS_HOST: ${REDIS_HOST}
      REDIS_PORT: ${REDIS_PORT}
      USER: ${USER}
      PASSWORD: ${PASSWORD}
      AGENT_SINE: ${AGENT_SINE}
      TERMINAL_ID: ${TERMINAL_ID}
      TARGET: ${TARGET}
      ISOCOUNTRY: ${ISOCOUNTRY}
    depends_on:
      - redis
